apiVersion: v1
kind: Service
metadata:
  name: java-prometheus-service
  namespace: java-prometheus
  
spec:
  selector:
    app: keda-java-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
  type: ClusterIP

